MVL-589: Added PythonPip and PyTorch tutorials
MeVisLab/examples pull request #52
Opened 2023-05-17 08:49 UTC by sahehb

2023-05-17 12:14 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/thirdparty/pytorch/pytorchexample1.md
> +Installing additional Python packages into MeVisLab by using the `PythonPip` module requires administrative rights if you do not install into a user package. In addition to that, the installed packag
.. if you  did install MeVisLab for all users

2023-05-17 12:14 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/thirdparty/pytorch/pytorchexample1.md
> +If you are behind a proxy, you may have to set the **HTTP_PROXY** and **HTTPS_PROXY** environment variables to the hostname and port of your proxy. These are used by pip when accessing the internet.
proxy server

2023-05-22 06:28 UTC, sahehb commented on mevislab.github.io/content/tutorials/basicmechanisms/macromodules/pythonpip.md
> +  * packages can contain C-Extensions (since we use the same MSVC compiler resp. same GCC settings as Python 3 itself)
already resolved with Uwe

2023-05-22 06:42 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/basicmechanisms/macromodules/pythonpip.md
> +* **all installed packages with C-Extensions are release only**, so you can only import them in a release MeVisLab (under Windows)
I find it a bit confusing that there are 4 bullet point for two drawbacks - the first 3 lines belong together

2023-05-22 07:15 UTC, mrbean-bremen approved these changes

2023-05-22 09:59 UTC, merged

2023-05-22 10:04 UTC, aliahcodes requested changes
Request for changes in structure and language

2023-05-22 10:04 UTC, aliahcodes commented on mevislab.github.io/content/tutorials/thirdparty/pytorch/pytorchexample2.md
> +Add a `PythonImage` module to your workspace. We are using it to load an image from disk and execute the PyTorch network. Create your own MeVisLab package as described in [Example 2.1: Package creati
the disk

2023-05-22 10:04 UTC, aliahcodes commented on mevislab.github.io/content/tutorials/thirdparty/pytorch/pytorchexample2.md
> +Save your network containing the `PythonImage` module as *\*.mlab* file. Create a Macro Module as described in [Example 2.2: Global Macro modules](/tutorials/basicmechanisms/macromodules/globalmacrom
"Make sure to add a Python file while creating the macro module through the Macro Module Wizard"

2023-05-22 10:04 UTC, aliahcodes commented on mevislab.github.io/content/tutorials/thirdparty/pytorch/pytorchexample2.md
> +### Write the script file
"Content of the .script file" instead of current title

2023-05-22 10:21 UTC, sahehb commented on mevislab.github.io/content/tutorials/basicmechanisms/macromodules/pythonpip.md
> +* **all installed packages with C-Extensions are release only**, so you can only import them in a release MeVisLab (under Windows)
yes, Linux

2023-05-22 10:29 UTC, sahehb commented on mevislab.github.io/content/tutorials/thirdparty/pytorch.md
> +###
another headline still to come :)