CSOLabelRenderer Tutorial
MeVisLab/examples pull request #90
Opened 2024-02-23 10:20 UTC by SamaaAhm

2024-02-23 12:17 UTC, sahehb requested changes
see comments

2024-02-23 13:40 UTC, sahehb approved these changes

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/dataobjects/contours/contourexample6.md
> +labelString = 'Length: ' + str(round(cso.getLength(), 2)) + ' mm'
Same here:
```py
labelString = f'Length: {cso.getLength():.2f} mm'
```

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/dataobjects/contours/contourexample6.md
> +For labels shown on greyscale images, it makes sense to add a shadow to your labels. Open the panel of the `SoCSOVisualizationSettings` module and on tab *Misc* check option *Should render shadow*. T
remove "to your labels"
check option -> check the option
increases readability -> increases the readability

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/dataobjects/contours/contourexample6.md
> +You can also add multiple CSO editors to see the different options. Add the `SoCSORectangleEditor` module to your workspace and connect it to the `SoGroup` module. As we now have two different editor
which CSO to be rendered -> which CSO is to be rendered (or: will be rendered)

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/dataobjects/contours/contourexample6.md
> +  labelString = userData0 + str(round(cso.getLength(), 2)) + ' mm'
see above

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/dataobjects/contours/contourexample6.md
> +  labelString += userData2 + str(round(cso.getArea(), 2)) + ' mm^2'
same

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/shorts.md
> +Especially in large networks it is useful to see the state of the in- and output connectors of a module. By default, the module connectors do not show if data is available. Below image shows a `Dicom
input and output

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/shorts.md
> +In MeVisLab preferences dialog, you can see a checkbox *Show ML image state*. By default, the setting is *Off*.
In the ...

2024-03-08 14:09 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/shorts.md
> +After enabling *Show ML image state*, your network changes and the in- and output connectors appear red in case no data is available at the output.
input and output

2024-03-11 07:49 UTC, mrbean-bremen commented on mevislab.github.io/content/tutorials/dataobjects/contours/contourexample6.md
> +labelName = f"Distance: {cso.getId:.2f}"
It's `getId()` (wth the parenthesis)

2024-03-11 08:20 UTC, mrbean-bremen approved these changes

2024-03-11 08:24 UTC, merged